### ISSUE TITLE
Limited Radius Computable

### ISSUE THREAD

**Issue by Jackoslovakia** [lperezmo/viewshed#1]
I tested this out on the side of Mount Kilimanjaro, which supposedly is known for having one of the largest viewsheds on earth, and it is clear there is a maximum radius the program can achieve. It appears to be roughly 5 miles.

![image](https://user-images.githubusercontent.com/125230720/218355273-3f14d04c-0e63-4a56-83d5-8864494660ec.png)

**Comment by lperezmo** [comment]
![F53DB136-89B6-4101-B506-F80B4E6B4F5A](https://user-images.githubusercontent.com/61613934/218470483-78b612ed-4c6f-459a-ac73-fc5a7015f710.jpeg)

Yes, line 139 defines a maximum radius, which I was in fact planning to make smaller to help the map render faster. Feel free to make a fork of the repo or just download the HTML file and increase it to a value that works for you, thanks. 🙂
